/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Event } from './types';

export const INITIAL_EVENTS: Event[] = [
  // --- MUSIC CATEGORY (6 events) ---
  {
    id: 'evt-music-1',
    title: 'Bollywood Pop Fiesta feat. Live Symphony',
    description: 'Immerse yourself in a high-energy magical evening of famous Bollywood anthems recreated by national singers accompanied by a massive 40-piece live orchestra and modern electronic synthesis.',
    category: 'Music',
    date: 'June 12, 2026',
    time: '7:00 PM - 11:30 PM',
    locationName: 'Jio World Garden, BKC',
    city: 'Mumbai',
    coordinates: { x: 32, y: 38 },
    price: 1499,
    capacity: 450,
    tags: ['Bollywood', 'Concert', 'Live Music', 'Orchestra'],
    image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=800&auto=format&fit=crop',
    organizer: 'Percept Live Entertainment',
    popularity: 9.8,
    hasSeats: true
  },
  {
    id: 'evt-music-2',
    title: 'Bengaluru Sitar & Jazz Conclave',
    description: 'An ethereal musical synthesis where traditional Indian classical sitar ragas flow seamlessly with modern West Coast jazz structures, set within an acoustic paradise hall.',
    category: 'Music',
    date: 'June 13, 2026',
    time: '6:30 PM - 9:30 PM',
    locationName: 'Chowdiah Memorial Hall',
    city: 'Bengaluru',
    coordinates: { x: 48, y: 25 },
    price: 499,
    capacity: 200,
    tags: ['Jazz', 'Sitar', 'Classical Fusion', 'Melody'],
    image: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?q=80&w=800&auto=format&fit=crop',
    organizer: 'Indigo Music Collective',
    popularity: 9.2,
    hasSeats: true
  },
  {
    id: 'evt-music-3',
    title: 'Delhi Sufi Mehfil in the Ruins',
    description: 'Listen to hauntingly beautiful traditional qawwali and sufi lyrics sung under the ancient twinkling domes. Enjoy complementary spiced Kashmiri Kahwa tea.',
    category: 'Music',
    date: 'June 14, 2026',
    time: '7:30 PM - 10:30 PM',
    locationName: 'Lodi Gardens Amphitheatre',
    city: 'Delhi NCR',
    coordinates: { x: 65, y: 72 },
    price: 799,
    capacity: 150,
    tags: ['Sufi', 'Qawwali', 'Heritage', 'Acoustic'],
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
    organizer: 'Sufiyan Heritage Trust',
    popularity: 9.4,
    hasSeats: false
  },
  {
    id: 'evt-music-4',
    title: 'Hyderabad Bass & Laser Arena',
    description: 'A massive multi-laser neon EDM playground featuring heavy sub-bass regional drops, interactive synthesized live visual projection mapping on historic virtual monuments.',
    category: 'Music',
    date: 'June 19, 2026',
    time: '8:00 PM - Midnight',
    locationName: 'Gachibowli Outdoor Ground',
    city: 'Hyderabad',
    coordinates: { x: 22, y: 55 },
    price: 999,
    capacity: 650,
    tags: ['EDM', 'DJ', 'Laser Show', 'Dance', 'Nightlife'],
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800&auto=format&fit=crop',
    organizer: 'Sunburn Arena',
    popularity: 9.6,
    hasSeats: false
  },
  {
    id: 'evt-music-5',
    title: 'Mumbai Seaside Indie Sunset Acoustics',
    description: 'Join a beautiful, casual acoustic circle along the marine sunset promenade. Enjoy unplugged original tracks from stellar regional indie guitarists and beach breezes.',
    category: 'Music',
    date: 'June 20, 2026',
    time: '5:30 PM - 8:00 PM',
    locationName: 'Carter Road Promenade',
    city: 'Mumbai',
    coordinates: { x: 52, y: 45 },
    price: 0,
    capacity: 400,
    tags: ['Indie', 'Acoustic', 'Sunset', 'Seaside', 'Free'],
    image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=800&auto=format&fit=crop',
    organizer: 'Bandra Collective',
    popularity: 9.1,
    hasSeats: false
  },
  {
    id: 'evt-music-6',
    title: 'Classic Rock Tribute India Tour',
    description: 'Relive rock history. A raw energetic tribute show featuring professional covers of Led Zeppelin, Queen, and Pink Floyd in a high-octane pub arena with local craft drinks.',
    category: 'Music',
    date: 'June 21, 2026',
    time: '8:00 PM - 11:30 PM',
    locationName: 'Hard Rock Cafe, St. Marks Rd',
    city: 'Bengaluru',
    coordinates: { x: 78, y: 62 },
    price: 1250,
    capacity: 180,
    tags: ['Rock', 'Tribute Band', 'Classic Rock', 'Beer'],
    image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?q=80&w=800&auto=format&fit=crop',
    organizer: 'RockOn India Labs',
    popularity: 8.9,
    hasSeats: true
  },

  // --- FOOD CATEGORY (6 events) ---
  {
    id: 'evt-food-1',
    title: 'Deccani Biryani & Haleem Street Trail',
    description: 'Embark on a culinary discovery walk. Sample the legendary historical wood-fire slow-cooked Persian-blend Hyderabadi mutton biryani and rich cardamom ghee haleem.',
    category: 'Food',
    date: 'June 12, 2026',
    time: '12:00 PM - 5:00 PM',
    locationName: 'Charminar Food Plaza',
    city: 'Hyderabad',
    coordinates: { x: 18, y: 65 },
    price: 250,
    capacity: 350,
    tags: ['Biryani', 'Traditional', 'Haleem', 'Heritage Trail'],
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
    organizer: 'Hyderabad Heritage Foodies',
    popularity: 9.7,
    hasSeats: false
  },
  {
    id: 'evt-food-2',
    title: 'Khao Galli Gourmet Chaat Festival',
    description: 'Taste the signature street tangy crisps of Mumbai. Interactive pani-puri shells filled with ice-cold mint water, spicy ragda, and sweet date syrup custom mixed by local master chefs.',
    category: 'Food',
    date: 'June 13, 2026',
    time: '4:00 PM - 10:00 PM',
    locationName: 'Girgaum Chowpatty Arena',
    city: 'Mumbai',
    coordinates: { x: 35, y: 42 },
    price: 150,
    capacity: 600,
    tags: ['Chaat', 'Pani Puri', 'Street Food', 'Vegetarian'],
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?q=80&w=800&auto=format&fit=crop',
    organizer: 'Amchi Mumbai Food Collective',
    popularity: 9.5,
    hasSeats: false
  },
  {
    id: 'evt-food-3',
    title: 'Delhi Old City Mughal Feast Walk',
    description: 'Navigate ancient narrow lanes to access hidden spots cooking char-grilled juicy smoked seekh-kebabs, rich creamy butter curries, and giant piping-hot dry-fruit sweet jalebis.',
    category: 'Food',
    date: 'June 14, 2026',
    time: '5:00 PM - 9:30 PM',
    locationName: 'Chandni Chowk Heritage Walks',
    city: 'Delhi NCR',
    coordinates: { x: 60, y: 58 },
    price: 800,
    capacity: 100,
    tags: ['Mughlai', 'Kebabs', 'Street Food', 'Old Delhi'],
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop',
    organizer: 'Purani Dilli Spice Guild',
    popularity: 9.3,
    hasSeats: false
  },
  {
    id: 'evt-food-4',
    title: 'Filter Coffee & South Indian Dosa Carnival',
    description: 'Savour golden buttery thin Ghee Podi roast dosas with vibrant mint chutneys, and master the art of froth-stretching filter coffee in traditional brass tumblers.',
    category: 'Food',
    date: 'June 19, 2026',
    time: '7:30 AM - 11:30 AM',
    locationName: 'Mavalli Tiffin Room Garden',
    city: 'Bengaluru',
    coordinates: { x: 55, y: 22 },
    price: 350,
    capacity: 250,
    tags: ['Dosa', 'Filter Coffee', 'South Indian', 'Traditional'],
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?q=80&w=800&auto=format&fit=crop',
    organizer: 'Ooru Culinary Lovers',
    popularity: 9.1,
    hasSeats: false
  },
  {
    id: 'evt-food-5',
    title: 'Craft Chocolate & Mithai Fusion Bazaar',
    description: 'A luxurious tasting session featuring single-origin Indian western kakaos infused with traditional subcontinental cardamom, saffron pearls, and high-modern milk bar bites.',
    category: 'Food',
    date: 'June 20, 2026',
    time: '2:00 PM - 7:00 PM',
    locationName: 'Phoenix Palladium Courtyard',
    city: 'Mumbai',
    coordinates: { x: 28, y: 48 },
    price: 500,
    capacity: 300,
    tags: ['Dessert', 'Chocolate', 'Fusion', 'Luxurious'],
    image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?q=80&w=800&auto=format&fit=crop',
    organizer: 'Palace Confectioners',
    popularity: 8.8,
    hasSeats: true
  },
  {
    id: 'evt-food-6',
    title: 'Punjabi Clay Oven Dhaba Caravan',
    description: 'Feast in a gorgeous simulated highway rustic setup. Highlights include coal-baked buttery garlic naans, Punjabi dal makhani slow cooked for 18 hours, and giant brass cups of thick sweet lassi.',
    category: 'Food',
    date: 'June 21, 2026',
    time: '6:00 PM - 10:30 PM',
    locationName: 'NH 1 Highway Resort Compound',
    city: 'Delhi NCR',
    coordinates: { x: 82, y: 15 },
    price: 450,
    capacity: 400,
    tags: ['Punjabi', 'Lassi', 'Tandoor', 'Dhaba'],
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
    organizer: 'Bharat Dhaba Express',
    popularity: 9.0,
    hasSeats: false
  },

  // --- TECH CATEGORY (6 events) ---
  {
    id: 'evt-tech-1',
    title: 'Silicon Valley of India Founders Summit',
    description: 'Identify unicorn trajectories, network with top venture capitalists, and discuss scaling deeptech in India. Includes networking lunches and panels on AI spatial search.',
    category: 'Tech',
    date: 'June 12, 2026',
    time: '9:00 AM - 5:00 PM',
    locationName: 'KTPO Trade Center, Whitefield',
    city: 'Bengaluru',
    coordinates: { x: 75, y: 18 },
    price: 2000,
    capacity: 400,
    tags: ['Startups', 'Venture', 'AI', 'Networking'],
    image: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=800&auto=format&fit=crop',
    organizer: 'Ooru Tech Circle',
    popularity: 9.8,
    hasSeats: true
  },
  {
    id: 'evt-tech-2',
    title: 'Hyderabad AI Hackathon: Generative Labs',
    description: 'Assemble with India’s elite engineers inside Hyderabad’s largest tech sandbox. Pitch prototypes utilizing advanced LLMs and secure instant grants.',
    category: 'Tech',
    date: 'June 13, 2026',
    time: '9:00 AM - 9:00 PM',
    locationName: 'T-Hub Arena, Gachibowli',
    city: 'Hyderabad',
    coordinates: { x: 22, y: 12 },
    price: 250,
    capacity: 350,
    tags: ['AI', 'Generative', 'Programming', 'Hackathon'],
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=800&auto=format&fit=crop',
    organizer: 'Emerging Tech India Labs',
    popularity: 9.5,
    hasSeats: false
  },
  {
    id: 'evt-tech-3',
    title: 'Delhi National Web3 & Security Conclave',
    description: 'Learn best defensive practices against smart contract vulnerabilities and scalable cryptography solutions. Over thirty international industry keynote presenters.',
    category: 'Tech',
    date: 'June 14, 2026',
    time: '10:00 AM - 6:00 PM',
    locationName: 'Pragati Maidan Hall 5',
    city: 'Delhi NCR',
    coordinates: { x: 65, y: 48 },
    price: 1500,
    capacity: 500,
    tags: ['Blockchain', 'CyberSecurity', 'Web3', 'Workshops'],
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop',
    organizer: 'Delhi NCR Web3 Council',
    popularity: 9.0,
    hasSeats: true
  },
  {
    id: 'evt-tech-4',
    title: 'Robotics & Hardware Maker Space Expo',
    description: 'Demo advanced high-accuracy quadcopters, micro-controllers, and smart wearable medical IoT gadgets rigged by brilliant engineering undergrads.',
    category: 'Tech',
    date: 'June 19, 2026',
    time: '10:00 AM - 5:00 PM',
    locationName: 'IISc Tech Incubation Hall',
    city: 'Bengaluru',
    coordinates: { x: 42, y: 32 },
    price: 150,
    capacity: 150,
    tags: ['Hardware', 'Robotics', 'Tinkering', 'Exhibition'],
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=800&auto=format&fit=crop',
    organizer: 'Robotics Alliance India',
    popularity: 8.7,
    hasSeats: false
  },
  {
    id: 'evt-tech-5',
    title: 'Mumbai FinTech Founders Roundtable',
    description: 'An intimate panel discussion charting real-time localized merchant payment flows, decentralized UPI protocols, and emerging AI risk assessing modules.',
    category: 'Tech',
    date: 'June 20, 2026',
    time: '3:00 PM - 7:00 PM',
    locationName: 'Naman Centre, BKC',
    city: 'Mumbai',
    coordinates: { x: 35, y: 55 },
    price: 1100,
    capacity: 120,
    tags: ['Fintech', 'UPI', 'Finance Panels', 'Banking'],
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=800&auto=format&fit=crop',
    organizer: 'Fintech Bharat Forum',
    popularity: 8.9,
    hasSeats: true
  },
  {
    id: 'evt-tech-6',
    title: 'IoT Embedded Sensors Hack Space',
    description: 'A full day of hands-on physical compute design with Raspberry Pi controllers, customized sensors, and wireless mesh networks inside a futuristic tech laboratory.',
    category: 'Tech',
    date: 'June 21, 2026',
    time: '9:00 AM - 6:30 PM',
    locationName: 'IIIT Hyderabad Labs Campus',
    city: 'Hyderabad',
    coordinates: { x: 50, y: 75 },
    price: 300,
    capacity: 100,
    tags: ['IoT', 'Raspberry Pi', 'Embedded Sys', 'Hardware'],
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop',
    organizer: 'Smart Compute Hyderabad',
    popularity: 8.6,
    hasSeats: false
  },

  // --- COMEDY CATEGORY (6 events) ---
  {
    id: 'evt-comedy-1',
    title: 'Mumbai Roast Battle Royale Unrated',
    description: 'Five of India’s boldest comics assemble for a relentless, fast-tempo evening of crowd roasts, self-deprecating banter, and raw observational comedy.',
    category: 'Comedy',
    date: 'June 12, 2026',
    time: '9:30 PM - 11:30 PM',
    locationName: 'The Tuning Fork, Khar',
    city: 'Mumbai',
    coordinates: { x: 28, y: 41 },
    price: 499,
    capacity: 120,
    tags: ['Roast', 'StandUp', 'Crowd Interaction', 'Nightlife'],
    image: 'https://images.unsplash.com/photo-1472289065668-ce650ac443d2?q=80&w=800&auto=format&fit=crop',
    organizer: 'Giggle Comedy Circle',
    popularity: 9.6,
    hasSeats: true
  },
  {
    id: 'evt-comedy-2',
    title: 'Delhi Late Night Stand-Up Showcase',
    description: 'Unfiltered laughter. Top local satellite comics throw punches at corporate life, traffic hazards, and old family dramas in an intimate club environment.',
    category: 'Comedy',
    date: 'June 13, 2026',
    time: '10:00 PM - Midnight',
    locationName: 'The Comedy Store, Saket',
    city: 'Delhi NCR',
    coordinates: { x: 62, y: 65 },
    price: 699,
    capacity: 150,
    tags: ['Standup', 'Late Night', 'Adult Jokes', 'Club'],
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    organizer: 'LaughLine India',
    popularity: 9.4,
    hasSeats: true
  },
  {
    id: 'evt-comedy-3',
    title: 'Bengaluru Live Improv Interactive Game',
    description: 'Zero scripts allowed! A chaotic night where the suggestions you shout dictate the hilarious scenes, musical raps, and rapid-fire characters created on stage.',
    category: 'Comedy',
    date: 'June 14, 2026',
    time: '5:30 PM - 7:30 PM',
    locationName: 'Alliance Francaise, Vasanth Nagar',
    city: 'Bengaluru',
    coordinates: { x: 48, y: 22 },
    price: 350,
    capacity: 250,
    tags: ['Improv', 'Interactive', 'Team Comedy', 'Family Friendly'],
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
    organizer: 'Ooru Improv Group',
    popularity: 9.1,
    hasSeats: true
  },
  {
    id: 'evt-comedy-4',
    title: 'Hyderabad Beer & Biryani Comedy Special',
    description: 'An interactive stand-up session loaded with regional jokes, and witty commentary on IT life, served alongside ice-cold craft beers.',
    category: 'Comedy',
    date: 'June 19, 2026',
    time: '8:00 PM - 10:30 PM',
    locationName: 'Heart Cup Cafe, Jubilee Hills',
    city: 'Hyderabad',
    coordinates: { x: 15, y: 52 },
    price: 599,
    capacity: 180,
    tags: ['StandUp', 'IT Jokes', 'Drinks', 'Fun Night'],
    image: 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?q=80&w=800&auto=format&fit=crop',
    organizer: 'Biryani Laugh Club',
    popularity: 9.3,
    hasSeats: false
  },
  {
    id: 'evt-comedy-5',
    title: 'Political Satire Live Comedy Hour',
    description: 'Witty, clever, and high-IQ satirical breakdown of current events, global trends, media drama, and corporate jargon from national veteran satirists.',
    category: 'Comedy',
    date: 'June 20, 2026',
    time: '6:00 PM - 8:00 PM',
    locationName: 'India Habitat Centre',
    city: 'Delhi NCR',
    coordinates: { x: 72, y: 50 },
    price: 400,
    capacity: 300,
    tags: ['Satire', 'Political Humor', 'Sarcasm', 'Thoughtful'],
    image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?q=80&w=800&auto=format&fit=crop',
    organizer: 'Sarcastic Citizens Guild',
    popularity: 8.8,
    hasSeats: true
  },
  {
    id: 'evt-comedy-6',
    title: 'Humming Standups Open Mic Night',
    description: 'Witness the birth of brilliant new punchlines! Come watch 10 aspiring comedians test fresh jokes, alongside a guest headline set from a stellar national comic.',
    category: 'Comedy',
    date: 'June 21, 2026',
    time: '7:30 PM - 10:00 PM',
    locationName: 'The Humming Tree, Indiranagar',
    city: 'Bengaluru',
    coordinates: { x: 82, y: 55 },
    price: 200,
    capacity: 100,
    tags: ['OpenMic', 'Raw', 'Cafe Show', 'Beer'],
    image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?q=80&w=800&auto=format&fit=crop',
    organizer: 'Ooru Standup Collective',
    popularity: 8.5,
    hasSeats: false
  },

  // --- ART CATEGORY (6 events) ---
  {
    id: 'evt-art-1',
    title: 'Bengaluru Clay-Throwing & Pottery Jam',
    description: 'Work with rotating clay wheels and premium terracotta compounds. Master-potters from around the state guide you in crafting your own customized glaze cups and structural plant pots.',
    category: 'Art',
    date: 'June 12, 2026',
    time: '3:00 PM - 6:00 PM',
    locationName: 'Clay Station, HSR Layout',
    city: 'Bengaluru',
    coordinates: { x: 40, y: 48 },
    price: 850,
    capacity: 50,
    tags: ['Pottery', 'Clay', 'Crafts', 'Workshop'],
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=800&auto=format&fit=crop',
    organizer: 'HSR Artisans Trust',
    popularity: 9.3,
    hasSeats: true
  },
  {
    id: 'evt-art-2',
    title: 'Mumbai Contemporary Biennial Gallery Walk',
    description: 'A curated visual tour exploring stunning installation galleries, spatial vector paintings, and progressive digital art canvas exhibits from Asia’s finest modern painters.',
    category: 'Art',
    date: 'June 13, 2026',
    time: '11:00 AM - 4:00 PM',
    locationName: 'Jehangir Art Gallery, Kala Ghoda',
    city: 'Mumbai',
    coordinates: { x: 26, y: 40 },
    price: 0,
    capacity: 200,
    tags: ['Gallery', 'Painting', 'Exhibition', 'Free'],
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    organizer: 'Kala Ghoda Art Cooperative',
    popularity: 9.6,
    hasSeats: false
  },
  {
    id: 'evt-art-3',
    title: 'Lodi Art District Mural & Graffiti Tour',
    description: 'Walk through Delhi’s spectacular open-air public art museum. Photograph and discover the rich historical narratives behind towering 30-foot murals styled by international creators.',
    category: 'Art',
    date: 'June 14, 2026',
    time: '4:00 PM - 6:30 PM',
    locationName: 'Lodi Colony Open Gallery',
    city: 'Delhi NCR',
    coordinates: { x: 55, y: 52 },
    price: 300,
    capacity: 120,
    tags: ['Murals', 'Street Art', 'Photography', 'Outdoor'],
    image: 'https://images.unsplash.com/photo-1561055657-b9e0bf0fa360?q=80&w=800&auto=format&fit=crop',
    organizer: 'Delhi Heritage Guild',
    popularity: 9.1,
    hasSeats: false
  },
  {
    id: 'evt-art-4',
    title: 'Hyderabad Tanjore Gold Foil Workshop',
    description: 'Learn the sacred traditional painting style using genuine 22-carat gold leaves, sparkling gemstones, and dense natural dyes to design historical royal icons.',
    category: 'Art',
    date: 'June 19, 2026',
    time: '10:30 AM - 2:30 PM',
    locationName: 'State Fine Arts Academy',
    city: 'Hyderabad',
    coordinates: { x: 38, y: 58 },
    price: 1800,
    capacity: 40,
    tags: ['Gold Foil', 'Traditional', 'Heritage', 'Workshop'],
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=800&auto=format&fit=crop',
    organizer: 'Deccan Craft Alliance',
    popularity: 9.5,
    hasSeats: true
  },
  {
    id: 'evt-art-5',
    title: 'Neon Brush & Glow Acrylic Lounge',
    description: 'Unleash your creativity under immersive ultraviolet lighting! Splash fluorescent paints on your custom black canvases while vibing to synthwave sub-bass frequencies.',
    category: 'Art',
    date: 'June 20, 2026',
    time: '6:30 PM - 9:30 PM',
    locationName: 'The Social Foundry, BKC',
    city: 'Mumbai',
    coordinates: { x: 42, y: 50 },
    price: 1200,
    capacity: 80,
    tags: ['Neon Painting', 'Lounge', 'Creative', 'Party'],
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=800&auto=format&fit=crop',
    organizer: 'Neon Paint India Collective',
    popularity: 9.2,
    hasSeats: true
  },
  {
    id: 'evt-art-6',
    title: 'Deccan Miniature Art Restoration Showcase',
    description: 'Watch professional archaeological restorers conserve fragile 400-year-old Mughal court miniatures, and participate in fine-brush preservation practices.',
    category: 'Art',
    date: 'June 21, 2026',
    time: '2:00 PM - 5:00 PM',
    locationName: 'Salarmujang Museum Campus',
    city: 'Hyderabad',
    coordinates: { x: 48, y: 68 },
    price: 450,
    capacity: 150,
    tags: ['Museum', 'Miniatures', 'History', 'Conservation'],
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=800&auto=format&fit=crop',
    organizer: 'Nizam Museum Circle',
    popularity: 8.9,
    hasSeats: false
  },
  
  // --- SPORTS CATEGORY (6 events) ---
  {
    id: 'evt-sports-1',
    title: 'Pro Kabaddi League Elite Clash',
    description: 'Witness the intense, raw athletic battles of native Indian wrestling. Top franchise teams lock horns in a high-octane stadium packed with local chants, drums, and spotlight pyro.',
    category: 'Sports',
    date: 'June 12, 2026',
    time: '7:30 PM - 10:00 PM',
    locationName: 'Gachibowli Indoor Stadium',
    city: 'Hyderabad',
    coordinates: { x: 26, y: 44 },
    price: 350,
    capacity: 1200,
    tags: ['Kabaddi', 'Live Match', 'Stadium', 'High Energy'],
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=800&auto=format&fit=crop',
    organizer: 'Pro Kabaddi Corp',
    popularity: 9.8,
    hasSeats: true
  },
  {
    id: 'evt-sports-2',
    title: 'Indiranagar Night Turf Football Showdown',
    description: 'An lightning-fast 5v5 floodlit amateur football tournament. Register your squad, test your tactical vectors under night beams, and win gold-stamped custom trophies.',
    category: 'Sports',
    date: 'June 13, 2026',
    time: '8:00 PM - Midnight',
    locationName: 'Dribble Arena, Indiranagar',
    city: 'Bengaluru',
    coordinates: { x: 62, y: 55 },
    price: 1500,
    capacity: 64,
    tags: ['Football', 'Night Turf', 'Floodlights', 'Soccer'],
    image: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?q=80&w=800&auto=format&fit=crop',
    organizer: 'Bengaluru Urban Turfs',
    popularity: 9.4,
    hasSeats: true
  },
  {
    id: 'evt-sports-3',
    title: 'Marine Drive Sunrise Cyclothon & Run',
    description: 'Join thousands of fitness enthusiasts in a breezy 15-kilometer cycling loop and coastal run along Mumbai’s majestic seaside curves, supported by timing-chips and hydrators.',
    category: 'Sports',
    date: 'June 14, 2026',
    time: '5:30 AM - 9:00 AM',
    locationName: 'Nariman Point Plaza',
    city: 'Mumbai',
    coordinates: { x: 34, y: 56 },
    price: 499,
    capacity: 1500,
    tags: ['Cyclothon', 'Running', 'Marine Drive', 'Fitness'],
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=800&auto=format&fit=crop',
    organizer: 'Mumbai Athletic Trust',
    popularity: 9.5,
    hasSeats: false
  },
  {
    id: 'evt-sports-4',
    title: 'Delhi National Padel Tennis Open',
    description: 'Experience the fastest-growing modern racket sport. A highly action-packed glass-walled layout tournament matching premier regional padel athletes.',
    category: 'Sports',
    date: 'June 19, 2026',
    time: '9:00 AM - 6:00 PM',
    locationName: 'Padel Court Club, Gurugram',
    city: 'Delhi NCR',
    coordinates: { x: 45, y: 65 },
    price: 800,
    capacity: 100,
    tags: ['Padel Tennis', 'Tournament', 'Rackets', 'Gym'],
    image: 'https://images.unsplash.com/photo-1545809074-59472b3f5ecc?q=80&w=800&auto=format&fit=crop',
    organizer: 'All India Padel Association',
    popularity: 9.1,
    hasSeats: true
  },
  {
    id: 'evt-sports-5',
    title: 'Hyderabad Formula E Circuit Showcase',
    description: 'Behold the incredible electric cyber-speed hypercars scream across Hussain Sagar lake curves. Hear from expert mechanics, engineering leads and test racing virtual simulators.',
    category: 'Sports',
    date: 'June 20, 2026',
    time: '11:00 AM - 5:00 PM',
    locationName: 'NTR Gardens Track',
    city: 'Hyderabad',
    coordinates: { x: 42, y: 46 },
    price: 1999,
    capacity: 2000,
    tags: ['Racing', 'Formula E', 'Supercars', 'Simulators'],
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=800&auto=format&fit=crop',
    organizer: 'Formula E India',
    popularity: 9.7,
    hasSeats: true
  },
  {
    id: 'evt-sports-6',
    title: 'Bengaluru FC Football Match Fan Arena',
    description: 'A massive live stadium screen arena featuring live commentator analysis, high-fidelity subwoofers, custom flags, and cold drinks with active fan club sing-alongs.',
    category: 'Sports',
    date: 'June 21, 2026',
    time: '6:30 PM - 9:30 PM',
    locationName: 'Kanteerava Fan Courtyard',
    city: 'Bengaluru',
    coordinates: { x: 50, y: 40 },
    price: 250,
    capacity: 500,
    tags: ['Soccer Fan', 'Live Screen', 'Cheering', 'Festival'],
    image: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?q=80&w=800&auto=format&fit=crop',
    organizer: 'West Block Blues Trust',
    popularity: 9.3,
    hasSeats: false
  }
];

export const MAP_BUILDINGS = [
  { name: 'Bengaluru Metro Hub', x: 45, y: 22, width: 14, height: 10, color: 'bg-indigo-500/10 border-indigo-500/30' },
  { name: 'Gateway of India Gate', x: 28, y: 46, width: 8, height: 8, color: 'bg-emerald-500/10 border-emerald-500/30' },
  { name: 'Charminar Heritage Block', x: 14, y: 63, width: 10, height: 10, color: 'bg-amber-500/10 border-amber-500/30' },
  { name: 'IISc DeepTech Incubator', x: 73, y: 14, width: 12, height: 12, color: 'bg-purple-500/10 border-purple-500/30' },
  { name: 'Pragati Maidan Convention', x: 62, y: 44, width: 11, height: 10, color: 'bg-rose-500/10 border-rose-500/30' }
];

export const MAP_ROADS = [
  // Horizontal Main Roads
  { name: 'Mahatma Gandhi Road', x1: 5, y1: 30, x2: 95, y2: 30 },
  { name: 'Outer Ring Road (ORR)', x1: 10, y1: 65, x2: 90, y2: 65 },
  // Vertical Main Roads
  { name: 'Gateway Boulevard', x1: 30, y1: 5, x2: 30, y2: 95 },
  { name: 'Tech Park Flyover', x1: 70, y1: 5, x2: 70, y2: 95 },
  { name: 'Lodi Heritage Lane', x1: 15, y1: 10, x2: 15, y2: 90 }
];

export const WATER_BODIES = [
  // Deep serene water path cutting across
  { path: 'M 15,0 Q 25,30 20,60 T 10,100 L 0,100 L 0,0 Z', name: 'Musi River' }
];
